version: '3'
services:
  database:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: eaglejump
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
